faq_list = [
    {"question": "Come posso restituire un articolo ordinato?", "answer": "Per restituire un articolo, devi accedere al tuo account Amazon, andare alla sezione 'I miei ordini' e selezionare l'ordine che desideri restituire. Clicca su 'Restituisci articoli' e segui le istruzioni. Puoi scegliere tra diverse modalità di restituzione, tra cui la stampa di un'etichetta di reso e la spedizione tramite corriere. Se il prodotto è difettoso o non conforme, potresti anche essere idoneo a un rimborso completo senza dover restituire l'articolo."},
    {"question": "Come posso contattare il Servizio Clienti di Amazon?", "answer": "Amazon offre diverse modalità di contatto per risolvere qualsiasi problema tu possa avere. Puoi accedere al Centro Assistenza clienti sul sito web di Amazon, dove troverai la possibilità di chattare con un agente, inviare un'email o parlare telefonicamente con un operatore. In caso di problemi con un ordine, il Servizio Clienti sarà in grado di assisterti con la restituzione, il rimborso o altre soluzioni."},
    {"question": "Cos'è Amazon Prime e come posso iscrivermi?", "answer": "Amazon Prime è un servizio in abbonamento che offre una serie di vantaggi esclusivi, come spedizioni gratuite in un giorno o in due giorni, accesso anticipato a offerte e sconti, streaming video e musicale, e molto altro. Puoi iscriverti ad Amazon Prime tramite il sito web di Amazon, dove puoi scegliere un piano mensile o annuale. Dopo l'iscrizione, potrai usufruire immediatamente dei benefici di Prime."},
    {"question": "Come posso porre una domanda su un prodotto?", "answer": "Per porre una domanda su un prodotto, vai alla pagina del prodotto stesso e cerca la sezione 'Domande e risposte dei clienti'. Qui, puoi inserire la tua domanda, che sarà visibile a tutti gli utenti che potranno rispondere. Inoltre, potrai vedere le domande già fatte da altri clienti e le relative risposte, che potrebbero darti ulteriori informazioni sul prodotto."},
    {"question": "Come posso gestire le mie opzioni di spedizione?", "answer": "Nel tuo account Amazon, puoi modificare le preferenze di spedizione. Puoi scegliere tra spedizioni standard gratuite o spedizioni veloci, a seconda dei tuoi desideri. Se sei un membro Amazon Prime, puoi usufruire della spedizione gratuita in un giorno. Inoltre, puoi aggiornare l'indirizzo di spedizione o modificare le informazioni di pagamento direttamente dalle impostazioni del tuo account."},
    {"question": "Come posso fare un ordine su Amazon?", "answer": "Per fare un ordine su Amazon, basta accedere al tuo account e cercare i prodotti che desideri acquistare. Aggiungi gli articoli al carrello e procedi al checkout. Qui, potrai inserire l'indirizzo di spedizione, scegliere il metodo di pagamento e selezionare le opzioni di spedizione. Dopo aver confermato l'ordine, riceverai una email di conferma con il numero di tracciamento, se disponibile."},
    {"question": "Come posso verificare lo stato del mio ordine?", "answer": "Puoi verificare lo stato del tuo ordine in qualsiasi momento accedendo alla sezione 'I miei ordini' del tuo account Amazon. Qui troverai una lista di tutti gli ordini effettuati, con informazioni dettagliate sullo stato di ciascun ordine, comprese le date di spedizione e consegna previste."},
    {"question": "Quali metodi di pagamento sono accettati su Amazon?", "answer": "Amazon accetta vari metodi di pagamento, tra cui carte di credito, carte prepagate, bonifici bancari, e gift card Amazon. Puoi aggiungere un metodo di pagamento nel tuo account e utilizzarlo per acquistare prodotti sul sito. Se hai un saldo disponibile su una gift card Amazon, verrà utilizzato automaticamente al momento del pagamento."},
    {"question": "Come posso aggiornare le informazioni del mio account?", "answer": "Puoi aggiornare le informazioni del tuo account, come l'indirizzo di spedizione, i dettagli di pagamento e le preferenze di notifica, accedendo alla sezione 'Il mio account'. Qui puoi anche modificare la tua password, gestire gli abbonamenti e visualizzare le tue informazioni di fatturazione."},
    {"question": "Come posso annullare un ordine?", "answer": "Gli ordini Amazon vengono generalmente evasi in tempi molto rapidi, quindi non è sempre possibile annullarli dopo averli effettuati. Tuttavia, se l'ordine non è stato ancora spedito, puoi annullarlo dalla sezione 'I miei ordini' e cliccando sull'opzione 'Annulla ordine'. Se l'ordine è già stato spedito, dovrai procedere con una restituzione."}
]
